'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.34014
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DettaglioErrori730Service
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://dettaglioerrori.p730.sanita.sogei.it/", ConfigurationName:="DettaglioErrori730Service.DettaglioErrori730")>  _
    Public Interface DettaglioErrori730
        
        'CODEGEN: Il parametro 'DatiOutputRichiesta' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DettaglioErrori(ByVal request As DettaglioErrori730Service.DettaglioErroriRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="DatiOutputRichiesta")> DettaglioErrori730Service.DettaglioErroriResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function DettaglioErroriAsync(ByVal request As DettaglioErrori730Service.DettaglioErroriRequest) As System.Threading.Tasks.Task(Of DettaglioErrori730Service.DettaglioErroriResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dettaglioerrori.p730.sanita.sogei.it/")>  _
    Partial Public Class datiInput
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pinCodeField As String
        
        Private protocolloField As String
        
        Private opzionale1Field As String
        
        Private opzionale2Field As String
        
        Private opzionale3Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property pinCode() As String
            Get
                Return Me.pinCodeField
            End Get
            Set
                Me.pinCodeField = value
                Me.RaisePropertyChanged("pinCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property protocollo() As String
            Get
                Return Me.protocolloField
            End Get
            Set
                Me.protocolloField = value
                Me.RaisePropertyChanged("protocollo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property opzionale1() As String
            Get
                Return Me.opzionale1Field
            End Get
            Set
                Me.opzionale1Field = value
                Me.RaisePropertyChanged("opzionale1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property opzionale2() As String
            Get
                Return Me.opzionale2Field
            End Get
            Set
                Me.opzionale2Field = value
                Me.RaisePropertyChanged("opzionale2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property opzionale3() As String
            Get
                Return Me.opzionale3Field
            End Get
            Set
                Me.opzionale3Field = value
                Me.RaisePropertyChanged("opzionale3")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dettaglioerrori.p730.sanita.sogei.it/")>  _
    Partial Public Class dettaglioEsitoNegativo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codiceField As String
        
        Private descrizioneField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codice() As String
            Get
                Return Me.codiceField
            End Get
            Set
                Me.codiceField = value
                Me.RaisePropertyChanged("codice")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property descrizione() As String
            Get
                Return Me.descrizioneField
            End Get
            Set
                Me.descrizioneField = value
                Me.RaisePropertyChanged("descrizione")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dettaglioerrori.p730.sanita.sogei.it/")>  _
    Partial Public Class dettaglioEsitoPositivo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private csvField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=0)>  _
        Public Property csv() As Byte()
            Get
                Return Me.csvField
            End Get
            Set
                Me.csvField = value
                Me.RaisePropertyChanged("csv")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dettaglioerrori.p730.sanita.sogei.it/")>  _
    Partial Public Class esitiPositivi
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dettagliEsitoField As dettaglioEsitoPositivo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property dettagliEsito() As dettaglioEsitoPositivo
            Get
                Return Me.dettagliEsitoField
            End Get
            Set
                Me.dettagliEsitoField = value
                Me.RaisePropertyChanged("dettagliEsito")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dettaglioerrori.p730.sanita.sogei.it/")>  _
    Partial Public Class datiOutput
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private esitoChiamataField As String
        
        Private esitiPositiviField As esitiPositivi
        
        Private esitiNegativiField() As dettaglioEsitoNegativo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property esitoChiamata() As String
            Get
                Return Me.esitoChiamataField
            End Get
            Set
                Me.esitoChiamataField = value
                Me.RaisePropertyChanged("esitoChiamata")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property esitiPositivi() As esitiPositivi
            Get
                Return Me.esitiPositiviField
            End Get
            Set
                Me.esitiPositiviField = value
                Me.RaisePropertyChanged("esitiPositivi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property esitiNegativi() As dettaglioEsitoNegativo()
            Get
                Return Me.esitiNegativiField
            End Get
            Set
                Me.esitiNegativiField = value
                Me.RaisePropertyChanged("esitiNegativi")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="DettaglioErrori", WrapperNamespace:="http://dettaglioerrori.p730.sanita.sogei.it/", IsWrapped:=true)>  _
    Partial Public Class DettaglioErroriRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dettaglioerrori.p730.sanita.sogei.it/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public DatiInputRichiesta As DettaglioErrori730Service.datiInput
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DatiInputRichiesta As DettaglioErrori730Service.datiInput)
            MyBase.New
            Me.DatiInputRichiesta = DatiInputRichiesta
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="DettaglioErroriResponse", WrapperNamespace:="http://dettaglioerrori.p730.sanita.sogei.it/", IsWrapped:=true)>  _
    Partial Public Class DettaglioErroriResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://dettaglioerrori.p730.sanita.sogei.it/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public DatiOutputRichiesta As DettaglioErrori730Service.datiOutput
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DatiOutputRichiesta As DettaglioErrori730Service.datiOutput)
            MyBase.New
            Me.DatiOutputRichiesta = DatiOutputRichiesta
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DettaglioErrori730Channel
        Inherits DettaglioErrori730Service.DettaglioErrori730, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DettaglioErrori730Client
        Inherits System.ServiceModel.ClientBase(Of DettaglioErrori730Service.DettaglioErrori730)
        Implements DettaglioErrori730Service.DettaglioErrori730
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DettaglioErrori730Service_DettaglioErrori730_DettaglioErrori(ByVal request As DettaglioErrori730Service.DettaglioErroriRequest) As DettaglioErrori730Service.DettaglioErroriResponse Implements DettaglioErrori730Service.DettaglioErrori730.DettaglioErrori
            Return MyBase.Channel.DettaglioErrori(request)
        End Function
        
        Public Function DettaglioErrori(ByVal DatiInputRichiesta As DettaglioErrori730Service.datiInput) As DettaglioErrori730Service.datiOutput
            Dim inValue As DettaglioErrori730Service.DettaglioErroriRequest = New DettaglioErrori730Service.DettaglioErroriRequest()
            inValue.DatiInputRichiesta = DatiInputRichiesta
            Dim retVal As DettaglioErrori730Service.DettaglioErroriResponse = CType(Me,DettaglioErrori730Service.DettaglioErrori730).DettaglioErrori(inValue)
            Return retVal.DatiOutputRichiesta
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DettaglioErrori730Service_DettaglioErrori730_DettaglioErroriAsync(ByVal request As DettaglioErrori730Service.DettaglioErroriRequest) As System.Threading.Tasks.Task(Of DettaglioErrori730Service.DettaglioErroriResponse) Implements DettaglioErrori730Service.DettaglioErrori730.DettaglioErroriAsync
            Return MyBase.Channel.DettaglioErroriAsync(request)
        End Function
        
        Public Function DettaglioErroriAsync(ByVal DatiInputRichiesta As DettaglioErrori730Service.datiInput) As System.Threading.Tasks.Task(Of DettaglioErrori730Service.DettaglioErroriResponse)
            Dim inValue As DettaglioErrori730Service.DettaglioErroriRequest = New DettaglioErrori730Service.DettaglioErroriRequest()
            inValue.DatiInputRichiesta = DatiInputRichiesta
            Return CType(Me,DettaglioErrori730Service.DettaglioErrori730).DettaglioErroriAsync(inValue)
        End Function
    End Class
End Namespace
