'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.34014
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EsitoInvioDatiSpesa730Service
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://esitoinvio.p730.sanita.sogei.it/")>  _
    Partial Public Class Exception
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://esitoinvio.p730.sanita.sogei.it/")>  _
    Partial Public Class dettaglioEsitoNegativo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codiceField As String
        
        Private descrizioneField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codice() As String
            Get
                Return Me.codiceField
            End Get
            Set
                Me.codiceField = value
                Me.RaisePropertyChanged("codice")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property descrizione() As String
            Get
                Return Me.descrizioneField
            End Get
            Set
                Me.descrizioneField = value
                Me.RaisePropertyChanged("descrizione")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://esitoinvio.p730.sanita.sogei.it/")>  _
    Partial Public Class dettaglioEsitoPositivo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private protocolloField As String
        
        Private dataInvioField As String
        
        Private statoField As Integer
        
        Private descrizioneField As String
        
        Private nInviatiField As Long
        
        Private nAccoltiField As Long
        
        Private nWarningsField As Long
        
        Private nErroriField As Long
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property protocollo() As String
            Get
                Return Me.protocolloField
            End Get
            Set
                Me.protocolloField = value
                Me.RaisePropertyChanged("protocollo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property dataInvio() As String
            Get
                Return Me.dataInvioField
            End Get
            Set
                Me.dataInvioField = value
                Me.RaisePropertyChanged("dataInvio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property stato() As Integer
            Get
                Return Me.statoField
            End Get
            Set
                Me.statoField = value
                Me.RaisePropertyChanged("stato")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property descrizione() As String
            Get
                Return Me.descrizioneField
            End Get
            Set
                Me.descrizioneField = value
                Me.RaisePropertyChanged("descrizione")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property nInviati() As Long
            Get
                Return Me.nInviatiField
            End Get
            Set
                Me.nInviatiField = value
                Me.RaisePropertyChanged("nInviati")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property nAccolti() As Long
            Get
                Return Me.nAccoltiField
            End Get
            Set
                Me.nAccoltiField = value
                Me.RaisePropertyChanged("nAccolti")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property nWarnings() As Long
            Get
                Return Me.nWarningsField
            End Get
            Set
                Me.nWarningsField = value
                Me.RaisePropertyChanged("nWarnings")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property nErrori() As Long
            Get
                Return Me.nErroriField
            End Get
            Set
                Me.nErroriField = value
                Me.RaisePropertyChanged("nErrori")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://esitoinvio.p730.sanita.sogei.it/")>  _
    Partial Public Class datiOutput
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private esitoChiamataField As String
        
        Private descrizioneEsitoField As String
        
        Private esitiPositiviField() As dettaglioEsitoPositivo
        
        Private esitiNegativiField() As dettaglioEsitoNegativo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property esitoChiamata() As String
            Get
                Return Me.esitoChiamataField
            End Get
            Set
                Me.esitoChiamataField = value
                Me.RaisePropertyChanged("esitoChiamata")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property descrizioneEsito() As String
            Get
                Return Me.descrizioneEsitoField
            End Get
            Set
                Me.descrizioneEsitoField = value
                Me.RaisePropertyChanged("descrizioneEsito")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute("dettagliEsito", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property esitiPositivi() As dettaglioEsitoPositivo()
            Get
                Return Me.esitiPositiviField
            End Get
            Set
                Me.esitiPositiviField = value
                Me.RaisePropertyChanged("esitiPositivi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property esitiNegativi() As dettaglioEsitoNegativo()
            Get
                Return Me.esitiNegativiField
            End Get
            Set
                Me.esitiNegativiField = value
                Me.RaisePropertyChanged("esitiNegativi")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://esitoinvio.p730.sanita.sogei.it/")>  _
    Partial Public Class datiInput
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pinCodeField As String
        
        Private dataInizioField As String
        
        Private dataFineField As String
        
        Private protocolloField As String
        
        Private opzionale1Field As String
        
        Private opzionale2Field As String
        
        Private opzionale3Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property pinCode() As String
            Get
                Return Me.pinCodeField
            End Get
            Set
                Me.pinCodeField = value
                Me.RaisePropertyChanged("pinCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property dataInizio() As String
            Get
                Return Me.dataInizioField
            End Get
            Set
                Me.dataInizioField = value
                Me.RaisePropertyChanged("dataInizio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property dataFine() As String
            Get
                Return Me.dataFineField
            End Get
            Set
                Me.dataFineField = value
                Me.RaisePropertyChanged("dataFine")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property protocollo() As String
            Get
                Return Me.protocolloField
            End Get
            Set
                Me.protocolloField = value
                Me.RaisePropertyChanged("protocollo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property opzionale1() As String
            Get
                Return Me.opzionale1Field
            End Get
            Set
                Me.opzionale1Field = value
                Me.RaisePropertyChanged("opzionale1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property opzionale2() As String
            Get
                Return Me.opzionale2Field
            End Get
            Set
                Me.opzionale2Field = value
                Me.RaisePropertyChanged("opzionale2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property opzionale3() As String
            Get
                Return Me.opzionale3Field
            End Get
            Set
                Me.opzionale3Field = value
                Me.RaisePropertyChanged("opzionale3")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://esitoinvio.p730.sanita.sogei.it/", ConfigurationName:="EsitoInvioDatiSpesa730Service.EsitoInvioDatiSpesa730")>  _
    Public Interface EsitoInvioDatiSpesa730
        
        'CODEGEN: Il parametro 'DatiOutputRichiesta' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(EsitoInvioDatiSpesa730Service.Exception), Action:="", Name:="Exception"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EsitoInvii(ByVal request As EsitoInvioDatiSpesa730Service.EsitoInviiRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="DatiOutputRichiesta")> EsitoInvioDatiSpesa730Service.EsitoInviiResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function EsitoInviiAsync(ByVal request As EsitoInvioDatiSpesa730Service.EsitoInviiRequest) As System.Threading.Tasks.Task(Of EsitoInvioDatiSpesa730Service.EsitoInviiResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EsitoInvii", WrapperNamespace:="http://esitoinvio.p730.sanita.sogei.it/", IsWrapped:=true)>  _
    Partial Public Class EsitoInviiRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://esitoinvio.p730.sanita.sogei.it/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public DatiInputRichiesta As EsitoInvioDatiSpesa730Service.datiInput
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DatiInputRichiesta As EsitoInvioDatiSpesa730Service.datiInput)
            MyBase.New
            Me.DatiInputRichiesta = DatiInputRichiesta
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EsitoInviiResponse", WrapperNamespace:="http://esitoinvio.p730.sanita.sogei.it/", IsWrapped:=true)>  _
    Partial Public Class EsitoInviiResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://esitoinvio.p730.sanita.sogei.it/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public DatiOutputRichiesta As EsitoInvioDatiSpesa730Service.datiOutput
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DatiOutputRichiesta As EsitoInvioDatiSpesa730Service.datiOutput)
            MyBase.New
            Me.DatiOutputRichiesta = DatiOutputRichiesta
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface EsitoInvioDatiSpesa730Channel
        Inherits EsitoInvioDatiSpesa730Service.EsitoInvioDatiSpesa730, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EsitoInvioDatiSpesa730Client
        Inherits System.ServiceModel.ClientBase(Of EsitoInvioDatiSpesa730Service.EsitoInvioDatiSpesa730)
        Implements EsitoInvioDatiSpesa730Service.EsitoInvioDatiSpesa730
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EsitoInvioDatiSpesa730Service_EsitoInvioDatiSpesa730_EsitoInvii(ByVal request As EsitoInvioDatiSpesa730Service.EsitoInviiRequest) As EsitoInvioDatiSpesa730Service.EsitoInviiResponse Implements EsitoInvioDatiSpesa730Service.EsitoInvioDatiSpesa730.EsitoInvii
            Return MyBase.Channel.EsitoInvii(request)
        End Function
        
        Public Function EsitoInvii(ByVal DatiInputRichiesta As EsitoInvioDatiSpesa730Service.datiInput) As EsitoInvioDatiSpesa730Service.datiOutput
            Dim inValue As EsitoInvioDatiSpesa730Service.EsitoInviiRequest = New EsitoInvioDatiSpesa730Service.EsitoInviiRequest()
            inValue.DatiInputRichiesta = DatiInputRichiesta
            Dim retVal As EsitoInvioDatiSpesa730Service.EsitoInviiResponse = CType(Me,EsitoInvioDatiSpesa730Service.EsitoInvioDatiSpesa730).EsitoInvii(inValue)
            Return retVal.DatiOutputRichiesta
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EsitoInvioDatiSpesa730Service_EsitoInvioDatiSpesa730_EsitoInviiAsync(ByVal request As EsitoInvioDatiSpesa730Service.EsitoInviiRequest) As System.Threading.Tasks.Task(Of EsitoInvioDatiSpesa730Service.EsitoInviiResponse) Implements EsitoInvioDatiSpesa730Service.EsitoInvioDatiSpesa730.EsitoInviiAsync
            Return MyBase.Channel.EsitoInviiAsync(request)
        End Function
        
        Public Function EsitoInviiAsync(ByVal DatiInputRichiesta As EsitoInvioDatiSpesa730Service.datiInput) As System.Threading.Tasks.Task(Of EsitoInvioDatiSpesa730Service.EsitoInviiResponse)
            Dim inValue As EsitoInvioDatiSpesa730Service.EsitoInviiRequest = New EsitoInvioDatiSpesa730Service.EsitoInviiRequest()
            inValue.DatiInputRichiesta = DatiInputRichiesta
            Return CType(Me,EsitoInvioDatiSpesa730Service.EsitoInvioDatiSpesa730).EsitoInviiAsync(inValue)
        End Function
    End Class
End Namespace
