'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace InvioTelematicoSpeseSanitarie730p
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", ConfigurationName:="InvioTelematicoSpeseSanitarie730p.InvioTelematicoSS730pMtom")>  _
    Public Interface InvioTelematicoSS730pMtom
        
        'CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function inviaFileMtom(ByVal request As InvioTelematicoSpeseSanitarie730p.inviaFileMtomRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> InvioTelematicoSpeseSanitarie730p.inviaFileMtomResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function inviaFileMtomAsync(ByVal request As InvioTelematicoSpeseSanitarie730p.inviaFileMtomRequest) As System.Threading.Tasks.Task(Of InvioTelematicoSpeseSanitarie730p.inviaFileMtomResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/")>  _
    Partial Public Class proprietario
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codiceRegioneField As String
        
        Private codiceAslField As String
        
        Private codiceSSAField As String
        
        Private cfProprietarioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codiceRegione() As String
            Get
                Return Me.codiceRegioneField
            End Get
            Set
                Me.codiceRegioneField = value
                Me.RaisePropertyChanged("codiceRegione")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property codiceAsl() As String
            Get
                Return Me.codiceAslField
            End Get
            Set
                Me.codiceAslField = value
                Me.RaisePropertyChanged("codiceAsl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property codiceSSA() As String
            Get
                Return Me.codiceSSAField
            End Get
            Set
                Me.codiceSSAField = value
                Me.RaisePropertyChanged("codiceSSA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property cfProprietario() As String
            Get
                Return Me.cfProprietarioField
            End Get
            Set
                Me.cfProprietarioField = value
                Me.RaisePropertyChanged("cfProprietario")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/")>  _
    Partial Public Class ricevutaInvio
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codiceEsitoField As String
        
        Private dataAccoglienzaField As String
        
        Private descrizioneEsitoField As String
        
        Private dimensioneFileAllegatoField As String
        
        Private nomeFileAllegatoField As String
        
        Private protocolloField As String
        
        Private idErroreField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codiceEsito() As String
            Get
                Return Me.codiceEsitoField
            End Get
            Set
                Me.codiceEsitoField = value
                Me.RaisePropertyChanged("codiceEsito")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property dataAccoglienza() As String
            Get
                Return Me.dataAccoglienzaField
            End Get
            Set
                Me.dataAccoglienzaField = value
                Me.RaisePropertyChanged("dataAccoglienza")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property descrizioneEsito() As String
            Get
                Return Me.descrizioneEsitoField
            End Get
            Set
                Me.descrizioneEsitoField = value
                Me.RaisePropertyChanged("descrizioneEsito")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property dimensioneFileAllegato() As String
            Get
                Return Me.dimensioneFileAllegatoField
            End Get
            Set
                Me.dimensioneFileAllegatoField = value
                Me.RaisePropertyChanged("dimensioneFileAllegato")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property nomeFileAllegato() As String
            Get
                Return Me.nomeFileAllegatoField
            End Get
            Set
                Me.nomeFileAllegatoField = value
                Me.RaisePropertyChanged("nomeFileAllegato")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property protocollo() As String
            Get
                Return Me.protocolloField
            End Get
            Set
                Me.protocolloField = value
                Me.RaisePropertyChanged("protocollo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property idErrore() As String
            Get
                Return Me.idErroreField
            End Get
            Set
                Me.idErroreField = value
                Me.RaisePropertyChanged("idErrore")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="inviaFileMtom", WrapperNamespace:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", IsWrapped:=true)>  _
    Partial Public Class inviaFileMtomRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public nomeFileAllegato As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pincodeInvianteCifrato As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public datiProprietario As InvioTelematicoSpeseSanitarie730p.proprietario
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public opzionale1 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", Order:=4),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public opzionale2 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", Order:=5),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public opzionale3 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", Order:=6),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public documento() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nomeFileAllegato As String, ByVal pincodeInvianteCifrato As String, ByVal datiProprietario As InvioTelematicoSpeseSanitarie730p.proprietario, ByVal opzionale1 As String, ByVal opzionale2 As String, ByVal opzionale3 As String, ByVal documento() As Byte)
            MyBase.New
            Me.nomeFileAllegato = nomeFileAllegato
            Me.pincodeInvianteCifrato = pincodeInvianteCifrato
            Me.datiProprietario = datiProprietario
            Me.opzionale1 = opzionale1
            Me.opzionale2 = opzionale2
            Me.opzionale3 = opzionale3
            Me.documento = documento
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="inviaFileMtomResponse", WrapperNamespace:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", IsWrapped:=true)>  _
    Partial Public Class inviaFileMtomResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ejb.invioTelematicoSS730p.sanita.finanze.it/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As InvioTelematicoSpeseSanitarie730p.ricevutaInvio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As InvioTelematicoSpeseSanitarie730p.ricevutaInvio)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface InvioTelematicoSS730pMtomChannel
        Inherits InvioTelematicoSpeseSanitarie730p.InvioTelematicoSS730pMtom, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InvioTelematicoSS730pMtomClient
        Inherits System.ServiceModel.ClientBase(Of InvioTelematicoSpeseSanitarie730p.InvioTelematicoSS730pMtom)
        Implements InvioTelematicoSpeseSanitarie730p.InvioTelematicoSS730pMtom
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InvioTelematicoSpeseSanitarie730p_InvioTelematicoSS730pMtom_inviaFileMtom(ByVal request As InvioTelematicoSpeseSanitarie730p.inviaFileMtomRequest) As InvioTelematicoSpeseSanitarie730p.inviaFileMtomResponse Implements InvioTelematicoSpeseSanitarie730p.InvioTelematicoSS730pMtom.inviaFileMtom
            Return MyBase.Channel.inviaFileMtom(request)
        End Function
        
        Public Function inviaFileMtom(ByVal nomeFileAllegato As String, ByVal pincodeInvianteCifrato As String, ByVal datiProprietario As InvioTelematicoSpeseSanitarie730p.proprietario, ByVal opzionale1 As String, ByVal opzionale2 As String, ByVal opzionale3 As String, ByVal documento() As Byte) As InvioTelematicoSpeseSanitarie730p.ricevutaInvio
            Dim inValue As InvioTelematicoSpeseSanitarie730p.inviaFileMtomRequest = New InvioTelematicoSpeseSanitarie730p.inviaFileMtomRequest()
            inValue.nomeFileAllegato = nomeFileAllegato
            inValue.pincodeInvianteCifrato = pincodeInvianteCifrato
            inValue.datiProprietario = datiProprietario
            inValue.opzionale1 = opzionale1
            inValue.opzionale2 = opzionale2
            inValue.opzionale3 = opzionale3
            inValue.documento = documento
            Dim retVal As InvioTelematicoSpeseSanitarie730p.inviaFileMtomResponse = CType(Me,InvioTelematicoSpeseSanitarie730p.InvioTelematicoSS730pMtom).inviaFileMtom(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InvioTelematicoSpeseSanitarie730p_InvioTelematicoSS730pMtom_inviaFileMtomAsync(ByVal request As InvioTelematicoSpeseSanitarie730p.inviaFileMtomRequest) As System.Threading.Tasks.Task(Of InvioTelematicoSpeseSanitarie730p.inviaFileMtomResponse) Implements InvioTelematicoSpeseSanitarie730p.InvioTelematicoSS730pMtom.inviaFileMtomAsync
            Return MyBase.Channel.inviaFileMtomAsync(request)
        End Function
        
        Public Function inviaFileMtomAsync(ByVal nomeFileAllegato As String, ByVal pincodeInvianteCifrato As String, ByVal datiProprietario As InvioTelematicoSpeseSanitarie730p.proprietario, ByVal opzionale1 As String, ByVal opzionale2 As String, ByVal opzionale3 As String, ByVal documento() As Byte) As System.Threading.Tasks.Task(Of InvioTelematicoSpeseSanitarie730p.inviaFileMtomResponse)
            Dim inValue As InvioTelematicoSpeseSanitarie730p.inviaFileMtomRequest = New InvioTelematicoSpeseSanitarie730p.inviaFileMtomRequest()
            inValue.nomeFileAllegato = nomeFileAllegato
            inValue.pincodeInvianteCifrato = pincodeInvianteCifrato
            inValue.datiProprietario = datiProprietario
            inValue.opzionale1 = opzionale1
            inValue.opzionale2 = opzionale2
            inValue.opzionale3 = opzionale3
            inValue.documento = documento
            Return CType(Me,InvioTelematicoSpeseSanitarie730p.InvioTelematicoSS730pMtom).inviaFileMtomAsync(inValue)
        End Function
    End Class
End Namespace
